In [1]:
import numpy as np

In [6]:
a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
b = np.array([[9, 8, 7], [6, 5, 4], [3, 2, 1]])
print(a)
print(b)

# a+b
# a.T+b.T
# (a+b).T

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[9 8 7]
 [6 5 4]
 [3 2 1]]


array([[10, 10, 10],
       [10, 10, 10],
       [10, 10, 10]])

In [7]:
# a-b
# a.T-b.T
# (a-b).T

array([[-8, -6, -4],
       [-2,  0,  2],
       [ 4,  6,  8]])

In [8]:
#scalar multiplication
a = 2
u = np.array([1, 2, 3])
print(a * u)

[2 4 6]


In [9]:
#Dot product of two vectors
#For 2-D vectors , it is equivalent to matrix multiplication

u = np.array([1, 2, 3])
v = np.array([4, 5, 6])
print(u.dot(v))
print(1 * 4 + 2 * 5 + 3 * 6)

32
32


In [11]:
#Matrix Addition
a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
b = np.array([[9, 8, 7], [6, 5, 4], [3, 2, 1]])
print(a, end="a\n\n")
print(b, end="b\n\n")
print(a + b)

[[1 2 3]
 [4 5 6]
 [7 8 9]]a

[[9 8 7]
 [6 5 4]
 [3 2 1]]b

[[10 10 10]
 [10 10 10]
 [10 10 10]]


In [12]:
#Matrix Subtraction
a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
b = np.array([[9, 8, 7], [6, 5, 4], [3, 2, 1]])
print(a, end="a\n\n")
print(b, end="b\n\n")
print(a - b)

[[1 2 3]
 [4 5 6]
 [7 8 9]]a

[[9 8 7]
 [6 5 4]
 [3 2 1]]b

[[-8 -6 -4]
 [-2  0  2]
 [ 4  6  8]]


In [14]:
#Matrix and vector multiplication
a = ([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
b = ([9, 8, 7])
np.dot(a, b)

array([ 46, 118, 190])

In [15]:
#Matrix and matrix multiplication
a = ([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
b = ([[9, 8, 7], [6, 5, 4], [3, 2, 1]])
np.dot(a, b)

array([[ 30,  24,  18],
       [ 84,  69,  54],
       [138, 114,  90]])

In [17]:
#Transpose of a matrix
a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(a , end="a\n\n")
print(a.T)

[[1 2 3]
 [4 5 6]
 [7 8 9]]a

[[1 4 7]
 [2 5 8]
 [3 6 9]]


In [20]:
#create an identity matrix
I1 = np.eye(2)
I2 = np.eye(3)
print(I1 , end ="I1\n\n")
print(I2 , end ="I2\n\n")

[[1. 0.]
 [0. 1.]]I1

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]I2



In [24]:
import numpy as np

# Original matrix (singular)
a = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# Adjust one of the rows to make it linearly independent
a_non_singular = np.array([[1, 2, 3], 
                           [4, 5, 6], 
                           [7, 8, 10]])  # Change 9 to 10 to make rows independent

# Check the determinant
determinant = np.linalg.det(a_non_singular)
print(f"Determinant (non-singular matrix): {determinant}")

# If determinant is non-zero, calculate the inverse
if determinant != 0:
    inverse_matrix = np.linalg.inv(a_non_singular)
    print(f"Inverse of the matrix:\n{inverse_matrix}")


Determinant (non-singular matrix): -2.9999999999999996
Inverse of the matrix:
[[-0.66666667 -1.33333333  1.        ]
 [-0.66666667  3.66666667 -2.        ]
 [ 1.         -2.          1.        ]]
